In [8]:
import os
from glob import glob
import pandas as pd
import numpy as np
from io import StringIO
import scipy.io as io
from csv import reader
import linecache


In [ ]:
data_dir='/Users/cdla/Repository/menon/mds/stim_timing_files/'
os.mkdir(os.path.join(data_dir,'spm_onset_mask_files'))
os.mkdir(os.path.join(data_dir,'spm_onset_thresh_files'))

onset creation for mask runs

In [10]:
for subj in sorted([os.path.basename(x) for x in glob(os.path.join(data_dir,'TES*'))]):
    subjid=subj.replace('TES','0')
    data=pd.DataFrame()
    f = open(os.path.join(data_dir,subj,'cond_clearhit.1D'))
    for idx in range(1,sum(1 for row in f)+1):
        run_mat=dict()
        run_mat['sess_name']=[]
        run_mat['rest_exists']=1
        run_mat['sess_name'].append('mask%d'%idx)
        durations=[]
        run_onsets=[]
        names=[]
        for stim_file in sorted(glob(os.path.join(data_dir,subj,'cond*.csv'))):
            onsets=linecache.getline(stim_file,idx)
            onsets=onsets.split(',')
            onsets[-1]=onsets[-1][:-1]
            try:
                onsets=[float(onset) for onset in onsets]
            except: 
                onsets=[float(0)]
            durations.append(np.zeros(len(onsets),dtype=float))
            run_onsets.append(onsets)
            names.append(os.path.basename(stim_file).replace('.csv',''))
        run_mat['durations']=np.array(durations,dtype=object)
        run_mat['onsets']=np.array(run_onsets,dtype=object)
        run_mat['names']=np.array(names,dtype=object)
        io.savemat(os.path.join(data_dir,'spm_onset_mask_files',subjid+'_mask'+str(idx+1)+'.mat'),run_mat)

onset creation for thresh run

In [11]:
for subj in sorted([os.path.basename(x) for x in glob(os.path.join(data_dir,'TES*'))]):
    if subj=='TES010':
        continue
    else:
        subjid=subj.replace('TES','0')
        data=pd.DataFrame()
        idx=1
        run_mat=dict()
        durations=[]
        run_onsets=[]
        names=[]
        run_mat['sess_name']=[]
        run_mat['rest_exists']=1
        run_mat['sess_name'].append('thresh1')        
        for stim_file in sorted(glob(os.path.join(data_dir,subj,'thresh*.csv'))):
            onsets=linecache.getline(stim_file,idx)
            onsets=onsets.split(',')
            onsets[-1]=onsets[-1][:-1]
            onsets=[float(onset) for onset in onsets]
            durations.append(np.zeros(len(onsets),dtype=float))
            run_onsets.append(onsets)
            names.append(os.path.basename(stim_file).replace('.csv',''))
        run_mat['durations']=np.array(durations,dtype=object)
        run_mat['onsets']=np.array(run_onsets,dtype=object)
        run_mat['names']=np.array(names,dtype=object)
        io.savemat(os.path.join(data_dir,'spm_onset_thresh_files',subjid+'_thresh1.mat'),run_mat)

loading up an onset file to see structure

In [13]:
test=io.loadmat(os.path.join(data_dir,'spm_onset_thresh_files','0002_thresh1.mat'))
print(test)

{'__header__': b'MATLAB 5.0 MAT-file Platform: posix, Created on: Thu Mar 21 09:29:30 2019', '__version__': '1.0', '__globals__': [], 'sess_name': array(['thresh1'], dtype='<U7'), 'rest_exists': array([[1]]), 'durations': array([[array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]),
        array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]),
        array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]),
        array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]),
        array([[0., 0., 0., 0., 0., 0., 0., 0.]]), array([[0., 0., 0.]])]],
      dtype=object), 'onsets': array([[array([[ 79.1, 119.5, 134. , 139.4, 150.4, 170.7, 181.7, 218.6, 223.4,
        239.1, 261.2, 270.9, 275.6, 322.5, 333.4]]),
        array([[ 38.3,  43.7,  53.7,  94.2,  98.9, 108.8, 129.3, 191.9, 208. ,
        255.7, 290.7, 301. , 317.5]]),
        array([[ 64. ,  83.9,  89.5, 104.2, 124.4, 155.9, 160.8, 186.6, 197.3,
        202.5, 249.8, 285.4, 295.4, 31